services:
  frontend:
    container_name: frontend
    image: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    # ports:
    #   - 8001:8001
    volumes:
      - /app/database:/frontend/database
    restart: always

  backend:
    container_name: backend
    image: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    # ports:
    #   - 8002:8002
    restart: always

  proxy:
    container_name: proxy
    image: proxy
    build:
      context: ./proxy
      dockerfile: Dockerfile
    ports:
      - 80:80
      # - 8000:8000
    restart: always