services:
  frontend:
    image: dadarou/frontend
    build: frontend
    volumes:
      # VOLUME:CONTAINER_PATH
      - ~/website-volume/database:/app/database
    restart: always

  backend:
    image: dadarou/backend
    build: backend
    restart: always

  proxy:
    image: dadarou/proxy
    build: proxy
    ports:
      - 80:80
    restart: always